### ISSUE TITLE
Move to static generation?

### ISSUE THREAD

**Issue by oneiros** [PhlexUI/PhlexUI-web#84]
As you probably know, the website is currently down (see https://github.com/PhlexUI/phlex_ui/issues/45).

I suspect that the fact the website is a full-blown rails app makes hosting a bit more difficult.

But since the open sourcing of PhlexUI, the website has no dynamic parts whatsoever anymore as far as I can see. So how about generating static html instead and maybe just use GH pages for hosting?

The quick solution could be to create a github action that runs the app and crawls all pages.

Another interesting approach could be to see how well phlex (and PhlexUI) play with one of the existing ruby static site generators (bridgetown, middleman, jekyll or whatever).

The simplest solution could be to do something very much like phlex's website does (https://github.com/phlex-ruby/phlex.fun). It is mostly plain phlex components with just a little glue code to tie everything together.

What do you think? I would be happy to help with this effort.

**Comment by iseth** [comment]
Hey @oneiros again 😃
Yes I just saw this issue and the linked issue about the site being down. This has something to do with heroku and I'm not entirely sure what is going on. I reached out to George and hopfully we can get it back up asap.

As far as generating a static HTML site.... I could not be more supportive of that.

Looks like we have another repo to create and see where things go. I will start to dive into the phlex.fun repo and see how they wired things up. Maybe we can get some inspiration from them.
